apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-19c
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  serviceAccountName: oracle-sa
  serviceAccount: oracle-sa
